#!/usr/bin/env python3
"""
Automated Issue File Generator for Test Failures
Generates detailed issue files that Claude CLI can pick up and fix autonomously

Auto-generated by Claude CLI
"""

import os
import sys
import json
import argparse
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any


class IssueGenerator:
    """Generate issue files from test failures."""

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.issues_dir = project_root / "testing" / "issues"
        self.issues_dir.mkdir(parents=True, exist_ok=True)

    def generate_issue(
        self,
        test_name: str,
        test_file: str,
        error_message: str,
        stack_trace: str,
        component: str = "Unknown",
        priority: str = "MEDIUM",
        run_id: str = None,
        commit_sha: str = None
    ) -> Path:
        """
        Generate a detailed issue file for a test failure.

        Args:
            test_name: Name of the failing test
            test_file: Path to the test file
            error_message: Error message from the test
            stack_trace: Full stack trace
            component: Component being tested (Scraper, Processor, Notifier)
            priority: Issue priority (HIGH, MEDIUM, LOW)
            run_id: GitHub Actions run ID (if applicable)
            commit_sha: Git commit SHA (if applicable)

        Returns:
            Path to the generated issue file
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        issue_file = self.issues_dir / f"issue_{timestamp}.md"

        # Determine priority based on test type
        if "e2e" in test_file:
            priority = "HIGH"
        elif "integration" in test_file:
            priority = "MEDIUM"
        else:
            priority = "LOW"

        # Analyze root cause
        root_cause = self._analyze_root_cause(error_message, stack_trace)

        # Generate suggested fixes
        suggested_fixes = self._generate_suggested_fixes(
            error_message, component, test_name
        )

        # Generate reproduction steps
        reproduction_steps = self._generate_reproduction_steps(test_file, test_name)

        # Find related files
        related_files = self._find_related_files(component, test_file)

        # Create issue content
        content = self._create_issue_content(
            test_name=test_name,
            test_file=test_file,
            component=component,
            priority=priority,
            error_message=error_message,
            stack_trace=stack_trace,
            root_cause=root_cause,
            suggested_fixes=suggested_fixes,
            reproduction_steps=reproduction_steps,
            related_files=related_files,
            run_id=run_id,
            commit_sha=commit_sha,
            timestamp=timestamp
        )

        # Write issue file
        issue_file.write_text(content, encoding='utf-8')

        return issue_file

    def _analyze_root_cause(self, error_message: str, stack_trace: str) -> str:
        """Analyze the error and suggest root causes."""
        causes = []

        if "AssertionError" in error_message:
            causes.append("Assertion failed - expected value does not match actual")
        if "AttributeError" in error_message:
            causes.append("Attribute or method does not exist on object")
        if "KeyError" in error_message:
            causes.append("Dictionary key not found")
        if "TypeError" in error_message:
            causes.append("Type mismatch - wrong data type provided")
        if "ValueError" in error_message:
            causes.append("Value out of expected range or format")
        if "ConnectionError" in error_message or "Timeout" in error_message:
            causes.append("Network connectivity issue or timeout")
        if "FileNotFoundError" in error_message:
            causes.append("Required file or directory does not exist")
        if "ImportError" in error_message or "ModuleNotFoundError" in error_message:
            causes.append("Missing module or dependency")

        if not causes:
            causes.append("Unknown error - requires detailed investigation")

        return "\n".join(f"- {cause}" for cause in causes)

    def _generate_suggested_fixes(
        self, error_message: str, component: str, test_name: str
    ) -> str:
        """Generate suggested fixes based on error type."""
        fixes = []

        if "AssertionError" in error_message:
            fixes.append("Review the expected vs actual values in the assertion")
            fixes.append("Check if the mock data or fixtures need updating")
            fixes.append("Verify the component logic is correct")

        if "AttributeError" in error_message:
            fixes.append("Check if the class/object structure has changed")
            fixes.append("Verify the method or attribute name is correct")
            fixes.append("Ensure the object is properly initialized")

        if "ConnectionError" in error_message:
            fixes.append("Verify external dependencies are properly mocked")
            fixes.append("Check network connectivity (if testing real services)")
            fixes.append("Increase timeout values if needed")

        if not fixes:
            fixes.append("Read the test file and understand what it's testing")
            fixes.append("Review recent code changes to the component")
            fixes.append("Check if dependencies or configurations changed")
            fixes.append("Run the test locally to reproduce the issue")

        return "\n".join(f"{i+1}. {fix}" for i, fix in enumerate(fixes))

    def _generate_reproduction_steps(self, test_file: str, test_name: str) -> str:
        """Generate reproduction steps."""
        rel_test_file = test_file.replace(str(self.project_root), "").lstrip("\\/")

        steps = [
            f"Navigate to project root: `{self.project_root}`",
            f"Run: `pytest {rel_test_file}::{test_name} -v`",
            "Observe: Test should fail with the same error",
            "Analyze: Review the error message and stack trace"
        ]

        return "\n".join(f"{i+1}. {step}" for i, step in enumerate(steps))

    def _find_related_files(self, component: str, test_file: str) -> List[str]:
        """Find related source files."""
        related = [f"Test file: `{test_file}`"]

        # Map component to source directory
        component_map = {
            "Scraper": "src/scrapers/",
            "Processor": "src/processors/",
            "Notifier": "src/notifiers/"
        }

        if component in component_map:
            related.append(f"Component directory: `{component_map[component]}`")

        return related

    def _create_issue_content(
        self,
        test_name: str,
        test_file: str,
        component: str,
        priority: str,
        error_message: str,
        stack_trace: str,
        root_cause: str,
        suggested_fixes: str,
        reproduction_steps: str,
        related_files: List[str],
        run_id: str,
        commit_sha: str,
        timestamp: str
    ) -> str:
        """Create the complete issue file content."""
        now = datetime.now().isoformat()

        content = f"""# TEST FAILURE ISSUE
## Auto-Generated: {now}

---

## 🔴 FAILURE SUMMARY

**Test Case**: `{test_name}`
**Test File**: `{test_file}`
**Component**: `{component}`
**Priority**: `{priority}`

---

## 📝 ERROR DESCRIPTION

{error_message}

---

## 📚 STACK TRACE

```
{stack_trace}
```

---

## 🔍 ROOT CAUSE ANALYSIS

Possible root causes:
{root_cause}

---

## 🔧 SUGGESTED FIXES

{suggested_fixes}

---

## ✅ REPRODUCTION STEPS

{reproduction_steps}

---

## 📎 RELATED FILES

{chr(10).join(f'- {file}' for file in related_files)}

---

## 🤖 CLAUDE CLI INSTRUCTIONS

**This issue can be fixed autonomously by Claude CLI.**

To fix this issue:
1. Read this issue file
2. Read the failing test file: `{test_file}`
3. Analyze the error message and stack trace
4. Identify the root cause
5. Implement the fix in the appropriate source file
6. Run the test again: `pytest {test_file}::{test_name} -v`
7. Verify the test passes
8. Mark this issue as resolved

---

## 📊 TEST CONTEXT

- **Test Suite**: {self._get_test_suite_name(test_file)}
- **Test Run ID**: {run_id or 'N/A'}
- **Git Commit**: {commit_sha or 'N/A'}
- **Environment**: {'CI' if run_id else 'LOCAL'}
- **Timestamp**: {now}

---

## 📋 CHECKLIST FOR CLAUDE CLI

- [ ] Read and understand the issue
- [ ] Read the failing test file
- [ ] Identify the component being tested
- [ ] Analyze the root cause
- [ ] Implement the fix
- [ ] Run the test to verify fix
- [ ] Update related tests if needed
- [ ] Mark issue as resolved

---

**Status**: 🔴 OPEN
**Assigned To**: Claude CLI (Next Session)
**Created**: {now}
**Issue ID**: issue_{timestamp}
"""

        return content

    def _get_test_suite_name(self, test_file: str) -> str:
        """Get test suite name from file path."""
        if "unit" in test_file:
            return "Unit Tests"
        elif "integration" in test_file:
            return "Integration Tests"
        elif "e2e" in test_file:
            return "End-to-End Tests"
        elif "smoke" in test_file:
            return "Smoke Tests"
        return "Unknown"


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate issue files for test failures"
    )
    parser.add_argument(
        "--test-name",
        help="Name of the failing test",
        default="unknown_test"
    )
    parser.add_argument(
        "--test-file",
        help="Path to the test file",
        default="unknown_file.py"
    )
    parser.add_argument(
        "--error",
        help="Error message",
        default="Test failed"
    )
    parser.add_argument(
        "--stack-trace",
        help="Stack trace",
        default="No stack trace available"
    )
    parser.add_argument(
        "--component",
        help="Component being tested",
        default="Unknown"
    )
    parser.add_argument(
        "--run-id",
        help="GitHub Actions run ID",
        default=None
    )
    parser.add_argument(
        "--commit",
        help="Git commit SHA",
        default=None
    )

    args = parser.parse_args()

    # Determine project root
    project_root = Path(__file__).parent.parent.parent

    # Generate issue
    generator = IssueGenerator(project_root)
    issue_file = generator.generate_issue(
        test_name=args.test_name,
        test_file=args.test_file,
        error_message=args.error,
        stack_trace=args.stack_trace,
        component=args.component,
        run_id=args.run_id,
        commit_sha=args.commit
    )

    print(f"Issue file generated: {issue_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
