"""
Shared Test Fixtures and Configuration for Magic Bricks News Intelligence System
Auto-generated by Claude CLI

This file contains pytest fixtures, hooks, and configurations used across all test suites.
"""

import os
import sys
import json
import pytest
from datetime import datetime
from pathlib import Path
from unittest.mock import Mock, MagicMock
from typing import Dict, List, Any

# Add src directory to Python path for imports
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

# Test configuration
TEST_MODE = os.getenv("TEST_MODE", "true").lower() == "true"
CI_MODE = os.getenv("CI", "false").lower() == "true"


# ============================================================================
# SESSION-LEVEL FIXTURES (Run once per test session)
# ============================================================================

@pytest.fixture(scope="session")
def test_config():
    """Load test configuration."""
    return {
        "test_mode": TEST_MODE,
        "ci_mode": CI_MODE,
        "project_root": PROJECT_ROOT,
        "testing_dir": PROJECT_ROOT / "testing",
        "fixtures_dir": PROJECT_ROOT / "testing" / "fixtures",
        "debug_logs_dir": PROJECT_ROOT / "testing" / "debug_logs",
        "issues_dir": PROJECT_ROOT / "testing" / "issues",
    }


@pytest.fixture(scope="session")
def ensure_test_directories(test_config):
    """Ensure all required test directories exist."""
    directories = [
        test_config["debug_logs_dir"],
        test_config["issues_dir"],
        test_config["fixtures_dir"],
    ]
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
    return test_config


# ============================================================================
# MODULE-LEVEL FIXTURES (Run once per test module)
# ============================================================================

@pytest.fixture(scope="module")
def sample_news_data():
    """Sample news article data for testing."""
    return {
        "real_estate_news": {
            "title": "Mumbai property prices up 4.9% in Q4 2026",
            "source": "Economic Times",
            "url": "https://economictimes.indiatimes.com/news/property-prices",
            "published_at": "2026-01-15T10:30:00Z",
            "category": "real_estate",
            "priority": 7,
            "content": "Property prices in Mumbai witnessed a 4.9% increase in Q4 2026..."
        },
        "celebrity_deal": {
            "title": "Virat Kohli buys ₹34 Cr Worli apartment",
            "source": "Livemint",
            "url": "https://www.livemint.com/news/celebrity-property",
            "published_at": "2026-01-16T08:00:00Z",
            "category": "celebrity_deal",
            "priority": 9,
            "celebrity": "Virat Kohli",
            "amount": 34.0,
            "location": "Worli, Mumbai",
            "stamp_duty": 2.04,
            "content": "Cricketer Virat Kohli has purchased a luxury apartment..."
        },
        "infrastructure": {
            "title": "Mumbai Metro Line 3 to start operations by March 2026",
            "source": "PIB",
            "url": "https://pib.gov.in/PressReleaseIframePage.aspx?PRID=123456",
            "published_at": "2026-01-20T14:00:00Z",
            "category": "infrastructure",
            "priority": 8,
            "content": "The Mumbai Metro Line 3 (Colaba-SEEPZ corridor) is set to..."
        },
        "policy": {
            "title": "PMAY-Urban 2.0: 8.56 Lakh Houses Sanctioned",
            "source": "Ministry of Housing",
            "url": "https://mohua.gov.in/press-release/pmay-update",
            "published_at": "2026-01-22T11:00:00Z",
            "category": "policy",
            "priority": 9,
            "scheme": "PMAY-Urban",
            "content": "The Pradhan Mantri Awas Yojana Urban 2.0 has sanctioned..."
        }
    }


@pytest.fixture(scope="module")
def sample_celebrities_data():
    """Sample celebrity database for testing."""
    return {
        "celebrities": [
            {
                "name": "Virat Kohli",
                "aliases": ["King Kohli", "Chikoo", "Run Machine"],
                "category": "Sports",
                "high_value_threshold": 5.0
            },
            {
                "name": "Shah Rukh Khan",
                "aliases": ["SRK", "King Khan", "Badshah"],
                "category": "Bollywood",
                "high_value_threshold": 10.0
            },
            {
                "name": "Sachin Tendulkar",
                "aliases": ["Master Blaster", "Little Master"],
                "category": "Sports",
                "high_value_threshold": 5.0
            },
            {
                "name": "Amitabh Bachchan",
                "aliases": ["Big B", "Shahenshah"],
                "category": "Bollywood",
                "high_value_threshold": 10.0
            }
        ]
    }


# ============================================================================
# FUNCTION-LEVEL FIXTURES (Run once per test function)
# ============================================================================

@pytest.fixture
def mock_http_response():
    """Mock HTTP response object."""
    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.text = "<html><body>Test content</body></html>"
    mock_response.json.return_value = {"success": True}
    mock_response.headers = {"Content-Type": "text/html"}
    return mock_response


@pytest.fixture
def mock_telegram_api():
    """Mock Telegram Bot API."""
    mock_telegram = Mock()
    mock_telegram.send_message.return_value = {
        "ok": True,
        "result": {
            "message_id": 12345,
            "date": 1705392000,
            "chat": {"id": 123456789, "type": "private"}
        }
    }
    return mock_telegram


@pytest.fixture
def mock_email_smtp():
    """Mock SMTP email server."""
    mock_smtp = Mock()
    mock_smtp.sendmail.return_value = {}
    mock_smtp.login.return_value = (220, b"Authentication successful")
    mock_smtp.quit.return_value = (221, b"Bye")
    return mock_smtp


@pytest.fixture
def mock_news_scraper():
    """Mock news scraper with sample data."""
    mock_scraper = Mock()
    mock_scraper.scrape.return_value = [
        {
            "title": "Test Article 1",
            "url": "https://example.com/article1",
            "published_at": "2026-01-30T10:00:00Z",
            "source": "Test Source"
        },
        {
            "title": "Test Article 2",
            "url": "https://example.com/article2",
            "published_at": "2026-01-30T11:00:00Z",
            "source": "Test Source"
        }
    ]
    return mock_scraper


@pytest.fixture
def mock_igrs_scraper():
    """Mock IGRS portal scraper."""
    mock_igrs = Mock()
    mock_igrs.search_by_name.return_value = [
        {
            "buyer_name": "Virat Kohli",
            "property_value": 34.0,
            "stamp_duty": 2.04,
            "location": "Worli, Mumbai",
            "document_number": "RGD/WRL/2026/001234",
            "registration_date": "2026-01-15"
        }
    ]
    mock_igrs.search_high_value.return_value = []
    return mock_igrs


@pytest.fixture
def mock_deduplicator():
    """Mock deduplicator processor."""
    mock_dedup = Mock()
    mock_dedup.is_duplicate.return_value = False
    mock_dedup.remove_duplicates.side_effect = lambda items: items
    return mock_dedup


@pytest.fixture
def mock_celebrity_matcher():
    """Mock celebrity matcher processor."""
    mock_matcher = Mock()
    mock_matcher.match.return_value = {
        "celebrity": "Virat Kohli",
        "amount": 34.0,
        "confidence": 95,
        "high_value": True
    }
    return mock_matcher


@pytest.fixture
def mock_categorizer():
    """Mock news categorizer."""
    mock_cat = Mock()
    mock_cat.categorize.return_value = {
        "category": "real_estate",
        "priority": 7,
        "tags": ["Mumbai", "property prices"]
    }
    return mock_cat


@pytest.fixture
def temp_config_file(tmp_path):
    """Create temporary config file for testing."""
    config_file = tmp_path / "test_config.json"
    config_data = {
        "sources": ["Economic Times", "Livemint"],
        "keywords": ["property", "real estate"],
        "enabled": True
    }
    config_file.write_text(json.dumps(config_data, indent=2))
    return config_file


@pytest.fixture
def temp_cache_file(tmp_path):
    """Create temporary cache file for testing."""
    cache_file = tmp_path / "test_cache.json"
    cache_data = {
        "sent_news": [],
        "last_updated": datetime.now().isoformat()
    }
    cache_file.write_text(json.dumps(cache_data, indent=2))
    return cache_file


# ============================================================================
# MOCK HTML RESPONSES
# ============================================================================

@pytest.fixture
def mock_economic_times_html():
    """Mock Economic Times article HTML."""
    return """
    <html>
        <head><title>Economic Times</title></head>
        <body>
            <div class="eachStory">
                <h2>Mumbai property prices up 4.9% in Q4 2026</h2>
                <time datetime="2026-01-15T10:30:00Z">Jan 15, 2026</time>
                <p>Property prices in Mumbai witnessed a significant increase...</p>
                <a href="/news/property-prices">Read more</a>
            </div>
            <div class="eachStory">
                <h2>Noida sees surge in rental demand</h2>
                <time datetime="2026-01-15T11:00:00Z">Jan 15, 2026</time>
                <p>Rental market in Noida has seen unprecedented growth...</p>
                <a href="/news/rental-market">Read more</a>
            </div>
        </body>
    </html>
    """


@pytest.fixture
def mock_igrs_maharashtra_html():
    """Mock Maharashtra IGRS portal HTML."""
    return """
    <html>
        <head><title>Maharashtra IGR</title></head>
        <body>
            <table id="property-deals">
                <thead>
                    <tr>
                        <th>Buyer Name</th>
                        <th>Property Value</th>
                        <th>Location</th>
                        <th>Stamp Duty</th>
                        <th>Document No</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Virat Kohli</td>
                        <td>34,00,00,000</td>
                        <td>Worli, Mumbai</td>
                        <td>2,04,00,000</td>
                        <td>RGD/WRL/2026/001234</td>
                    </tr>
                </tbody>
            </table>
        </body>
    </html>
    """


@pytest.fixture
def mock_rss_feed_xml():
    """Mock RSS feed XML."""
    return """
    <?xml version="1.0" encoding="UTF-8"?>
    <rss version="2.0">
        <channel>
            <title>PIB Press Releases</title>
            <description>Latest government announcements</description>
            <item>
                <title>PMAY-Urban 2.0: 8.56 Lakh Houses Sanctioned</title>
                <link>https://pib.gov.in/PressReleaseIframePage.aspx?PRID=123456</link>
                <pubDate>Mon, 22 Jan 2026 11:00:00 GMT</pubDate>
                <description>The Pradhan Mantri Awas Yojana Urban 2.0 has sanctioned...</description>
            </item>
            <item>
                <title>Union Budget 2026: Key Highlights</title>
                <link>https://pib.gov.in/PressReleaseIframePage.aspx?PRID=123457</link>
                <pubDate>Thu, 01 Feb 2026 11:30:00 GMT</pubDate>
                <description>Finance Minister presents Union Budget 2026...</description>
            </item>
        </channel>
    </rss>
    """


# ============================================================================
# PYTEST HOOKS
# ============================================================================

def pytest_configure(config):
    """Configure pytest before test run."""
    # Register custom markers
    config.addinivalue_line("markers", "unit: Unit tests")
    config.addinivalue_line("markers", "integration: Integration tests")
    config.addinivalue_line("markers", "e2e: End-to-end tests")
    config.addinivalue_line("markers", "smoke: Smoke tests")
    config.addinivalue_line("markers", "slow: Slow running tests")
    config.addinivalue_line("markers", "real: Tests using real services")
    config.addinivalue_line("markers", "security: Security tests")
    config.addinivalue_line("markers", "performance: Performance tests")
    config.addinivalue_line("markers", "flaky: Flaky tests with auto-retry")


def pytest_sessionstart(session):
    """Called at start of test session."""
    print("\n" + "=" * 80)
    print("MAGIC BRICKS NEWS INTELLIGENCE SYSTEM - TEST SUITE")
    print("=" * 80)
    print(f"Test Mode: {'CI' if CI_MODE else 'LOCAL'}")
    print(f"Python Version: {sys.version.split()[0]}")
    print(f"Project Root: {PROJECT_ROOT}")
    print("=" * 80 + "\n")


def pytest_sessionfinish(session, exitstatus):
    """Called at end of test session."""
    print("\n" + "=" * 80)
    print("TEST SESSION COMPLETED")
    print(f"Exit Status: {exitstatus}")
    print("=" * 80 + "\n")


@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Generate issue files for test failures."""
    outcome = yield
    report = outcome.get_result()

    if report.when == "call" and report.failed:
        # Generate issue file for failure
        generate_issue_file(item, report)


def generate_issue_file(item, report):
    """Generate issue file for failed test."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    issues_dir = PROJECT_ROOT / "testing" / "issues"
    issues_dir.mkdir(parents=True, exist_ok=True)

    issue_file = issues_dir / f"issue_{timestamp}.md"

    # Extract error info
    test_name = item.name
    test_file = str(Path(str(item.fspath)).relative_to(PROJECT_ROOT))
    error_message = str(report.longrepr)

    # Component from test file path
    if "scrapers" in test_file:
        component = "Scraper"
    elif "processors" in test_file:
        component = "Processor"
    elif "notifiers" in test_file:
        component = "Notifier"
    else:
        component = "Unknown"

    # Priority based on test type
    if "e2e" in test_file:
        priority = "HIGH"
    elif "integration" in test_file:
        priority = "MEDIUM"
    else:
        priority = "LOW"

    content = f"""# TEST FAILURE ISSUE
## Auto-Generated: {datetime.now().isoformat()}

---

## 🔴 FAILURE SUMMARY

**Test Case**: `{test_name}`
**Test File**: `{test_file}`
**Component**: `{component}`
**Priority**: `{priority}`

---

## 📝 ERROR DESCRIPTION

Test failed during execution. See stack trace below for details.

---

## 📚 STACK TRACE

```
{error_message}
```

---

## 🔍 ROOT CAUSE ANALYSIS

**To be analyzed by Claude CLI**

Possible causes:
1. Code change broke existing functionality
2. Mock data out of sync with actual implementation
3. External dependency failure
4. Test assertion needs updating
5. Race condition or timing issue

---

## 🔧 SUGGESTED FIXES

**To be determined by Claude CLI after analysis**

General steps:
1. Read the test file: `{test_file}`
2. Review recent changes to related source files
3. Check if mocks need updating
4. Verify test assertions are correct
5. Fix the underlying issue
6. Re-run test to verify fix

---

## ✅ REPRODUCTION STEPS

1. Navigate to project root: `D:\\Jasmine\\00001_Content_app\\News_Update`
2. Run: `pytest {test_file}::{test_name} -v`
3. Observe: Test should fail with same error

---

## 📎 RELATED FILES

- Test file: `{test_file}`
- Component: Check `src/` directory for related source files

---

## 🤖 CLAUDE CLI INSTRUCTIONS

**This issue can be fixed autonomously by Claude CLI.**

To fix this issue:
1. Read this issue file
2. Read the failing test file
3. Analyze the error and root cause
4. Implement the fix
5. Run the test again to verify
6. Mark this issue as resolved if test passes

---

## 📊 TEST CONTEXT

- **Test Suite**: {item.config.option.markexpr or 'All tests'}
- **Test Run ID**: run_{timestamp}
- **Environment**: {'CI' if CI_MODE else 'LOCAL'}

---

**Status**: 🔴 OPEN
**Assigned To**: Claude CLI (Next Session)
**Created**: {datetime.now().isoformat()}
"""

    issue_file.write_text(content, encoding='utf-8')
    print(f"\nTest failed: {test_name}")
    print(f"Issue file generated: {issue_file}")


# ============================================================================
# PYTEST PLUGINS
# ============================================================================

# Enable retry for flaky tests
pytest_plugins = ["pytest_retry"]


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def load_fixture_file(filename: str) -> str:
    """Load fixture file content."""
    fixture_path = PROJECT_ROOT / "testing" / "fixtures" / filename
    if fixture_path.exists():
        return fixture_path.read_text()
    raise FileNotFoundError(f"Fixture file not found: {filename}")


def save_test_output(test_name: str, data: Any):
    """Save test output for debugging."""
    output_dir = PROJECT_ROOT / "testing" / "debug_logs" / "test_outputs"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / f"{test_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(output_file, "w") as f:
        json.dump(data, f, indent=2)

    return output_file
