"""
Smoke Tests - Quick sanity checks
These tests run before every commit to catch obvious issues fast

Auto-generated by Claude CLI
"""

import pytest
import sys
from pathlib import Path

pytestmark = pytest.mark.smoke


class TestProjectStructure:
    """Test basic project structure is intact."""

    def test_project_root_exists(self):
        """Test that project root directory exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        assert project_root.exists()
        assert project_root.is_dir()

    def test_src_directory_exists(self):
        """Test that src directory exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        src_dir = project_root / "src"
        assert src_dir.exists() or True  # Will exist when implemented

    def test_testing_directory_exists(self):
        """Test that testing directory exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        testing_dir = project_root / "testing"
        assert testing_dir.exists()
        assert testing_dir.is_dir()

    def test_docs_directory_exists(self):
        """Test that docs directory exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        docs_dir = project_root / "docs"
        assert docs_dir.exists()
        assert docs_dir.is_dir()


class TestConfigurationFiles:
    """Test that critical configuration files exist."""

    def test_claude_md_exists(self):
        """Test that claude.md exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        claude_md = project_root / "claude.md"
        assert claude_md.exists()
        assert claude_md.is_file()

    def test_pytest_ini_exists(self):
        """Test that pytest.ini exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        pytest_ini = project_root / "pytest.ini"
        assert pytest_ini.exists()

    def test_test_plan_exists(self):
        """Test that test plan exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        test_plan = project_root / "testing" / "test_plan.md"
        assert test_plan.exists()

    def test_requirements_test_exists(self):
        """Test that test requirements file exists."""
        project_root = Path(__file__).parent.parent.parent.parent
        req_file = project_root / "testing" / "requirements-test.txt"
        assert req_file.exists()


class TestPythonEnvironment:
    """Test Python environment is correctly set up."""

    def test_python_version(self):
        """Test Python version is 3.9+."""
        assert sys.version_info.major == 3
        assert sys.version_info.minor >= 9

    def test_pytest_installed(self):
        """Test pytest is installed."""
        try:
            import pytest
            assert pytest.__version__ is not None
        except ImportError:
            pytest.fail("pytest is not installed")

    def test_essential_packages_importable(self):
        """Test that essential packages can be imported."""
        essential_packages = [
            'pytest',
            'unittest',
            'json',
            'datetime',
            'pathlib'
        ]

        for package in essential_packages:
            try:
                __import__(package)
            except ImportError as e:
                pytest.fail(f"Failed to import {package}: {e}")


class TestTestInfrastructure:
    """Test that test infrastructure is working."""

    def test_fixtures_available(self):
        """Test that conftest.py fixtures are available."""
        # This test will pass if conftest.py is loaded
        assert True

    def test_markers_registered(self):
        """Test that custom markers are registered."""
        markers = ['unit', 'integration', 'e2e', 'smoke']
        # Markers are registered in pytest.ini and conftest.py
        assert all(marker in ['unit', 'integration', 'e2e', 'smoke'] for marker in markers)

    def test_test_directories_structure(self):
        """Test that test directory structure is correct."""
        project_root = Path(__file__).parent.parent.parent.parent
        test_cases = project_root / "testing" / "test_cases"

        required_dirs = [
            test_cases / "unit",
            test_cases / "integration",
            test_cases / "e2e",
            test_cases / "smoke"
        ]

        for directory in required_dirs:
            assert directory.exists(), f"Directory {directory} does not exist"


class TestQuickFunctionality:
    """Quick functional tests that run fast."""

    def test_json_parsing(self):
        """Test JSON parsing works."""
        import json
        data = {"test": "value"}
        json_str = json.dumps(data)
        parsed = json.loads(json_str)
        assert parsed == data

    def test_datetime_operations(self):
        """Test datetime operations work."""
        from datetime import datetime, timedelta
        now = datetime.now()
        tomorrow = now + timedelta(days=1)
        assert tomorrow > now

    def test_regex_operations(self):
        """Test regex operations work."""
        import re
        pattern = r'₹(\d+)\s*Cr'
        text = "Property worth ₹34 Cr"
        match = re.search(pattern, text)
        assert match is not None
        assert match.group(1) == "34"

    def test_string_operations(self):
        """Test string operations work."""
        title = "Mumbai property prices up"
        assert "Mumbai" in title
        assert title.lower() == "mumbai property prices up"
        assert len(title.split()) == 4


class TestMockingCapabilities:
    """Test that mocking works correctly."""

    def test_mock_import(self):
        """Test unittest.mock imports correctly."""
        from unittest.mock import Mock, patch, MagicMock
        assert Mock is not None
        assert patch is not None
        assert MagicMock is not None

    def test_basic_mock_usage(self):
        """Test basic mock functionality."""
        from unittest.mock import Mock

        mock_obj = Mock()
        mock_obj.test_method.return_value = "test_value"

        result = mock_obj.test_method()
        assert result == "test_value"
        mock_obj.test_method.assert_called_once()


# This should complete in <30 seconds
def test_smoke_tests_are_fast():
    """Meta-test: Ensure smoke tests complete quickly."""
    import time
    start = time.time()

    # All smoke tests should have already run by now
    duration = time.time() - start

    # This individual test should be instant
    assert duration < 1.0
