"""
Integration Tests for Full Pipeline
Tests the complete workflow from scraping to notification

Auto-generated by Claude CLI
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime

pytestmark = pytest.mark.integration


class TestFullPipeline:
    """Test complete pipeline integration."""

    @pytest.mark.slow
    def test_full_pipeline_morning_digest(
        self,
        mock_news_scraper,
        mock_deduplicator,
        mock_categorizer,
        mock_telegram_api
    ):
        """
        Test Case: PI-IT-001
        Test complete morning digest workflow.
        Expected: News → Process → Notify
        """
        # Arrange
        scraped_news = mock_news_scraper.scrape.return_value
        assert len(scraped_news) == 2

        # Act - Simulate pipeline
        # 1. Scrape news
        news_items = scraped_news

        # 2. Deduplicate
        unique_items = mock_deduplicator.remove_duplicates(news_items)
        assert len(unique_items) == 2

        # 3. Categorize
        categorized_items = [mock_categorizer.categorize(item) for item in unique_items]
        assert len(categorized_items) == 2

        # 4. Send notification
        response = mock_telegram_api.send_message("Morning digest")
        assert response["ok"] == True

    def test_full_pipeline_event_alert(
        self,
        sample_news_data
    ):
        """
        Test Case: PI-IT-002
        Test complete event alert workflow.
        Expected: Event trigger → Scrape → Alert
        """
        # Arrange
        event_config = {
            "name": "Budget 2026",
            "date": "2026-02-01",
            "start_time": "10:30",
            "end_time": "18:00",
            "frequency_minutes": 15
        }

        # Act - Simulate event workflow
        is_event_active = True  # Event day
        is_within_hours = True  # Within 10:30-18:00

        # Assert
        assert is_event_active == True
        assert is_within_hours == True
        # Pipeline should send alerts every 15 minutes

    def test_scraper_to_processor(
        self,
        mock_news_scraper,
        mock_deduplicator
    ):
        """
        Test Case: PI-IT-003
        Test data flow from scraper to processor.
        Expected: Data flows correctly
        """
        # Arrange
        scraped = mock_news_scraper.scrape.return_value

        # Act
        processed = mock_deduplicator.remove_duplicates(scraped)

        # Assert
        assert len(processed) == len(scraped)
        assert isinstance(processed, list)

    def test_processor_to_notifier(
        self,
        mock_categorizer,
        mock_telegram_api
    ):
        """
        Test Case: PI-IT-004
        Test data flow from processor to notifier.
        Expected: Notifications sent
        """
        # Arrange
        news_item = {"title": "Test news", "category": "real_estate"}
        categorized = mock_categorizer.categorize.return_value

        # Act
        notification_response = mock_telegram_api.send_message("Test message")

        # Assert
        assert notification_response["ok"] == True

    def test_deduplication_in_pipeline(self):
        """
        Test Case: PI-IT-005
        Test deduplication within full pipeline.
        Expected: Only unique news sent
        """
        # Arrange
        news_items = [
            {"title": "Mumbai prices up", "url": "https://example.com/1"},
            {"title": "Mumbai prices up", "url": "https://example.com/1"},  # Duplicate
            {"title": "Delhi rents down", "url": "https://example.com/2"}
        ]

        # Act - Deduplicate
        seen = set()
        unique_items = []
        for item in news_items:
            identifier = f"{item['title']}|{item['url']}"
            if identifier not in seen:
                seen.add(identifier)
                unique_items.append(item)

        # Assert
        assert len(unique_items) == 2
        assert unique_items[0]["title"] == "Mumbai prices up"
        assert unique_items[1]["title"] == "Delhi rents down"

    def test_celebrity_matching_in_pipeline(
        self,
        sample_celebrities_data
    ):
        """
        Test Case: PI-IT-006
        Test celebrity detection in pipeline.
        Expected: Celebrity news flagged
        """
        # Arrange
        news = {"title": "Virat Kohli buys ₹34 Cr apartment", "content": "..."}
        celebs = sample_celebrities_data["celebrities"]

        # Act - Match celebrity
        matched = [c for c in celebs if c["name"] in news["title"]]

        # Assert
        assert len(matched) == 1
        assert matched[0]["name"] == "Virat Kohli"
        # Should be flagged as high-priority

    def test_categorization_in_pipeline(self):
        """
        Test Case: PI-IT-007
        Test news categorization in pipeline.
        Expected: Categories assigned correctly
        """
        # Arrange
        news_items = [
            {"title": "Mumbai property prices up", "content": "real estate market..."},
            {"title": "Metro Line 3 opens", "content": "infrastructure project..."},
            {"title": "PMAY scheme updated", "content": "housing policy..."}
        ]

        # Act - Categorize based on keywords
        def categorize(news):
            if "property" in news["title"] or "prices" in news["title"]:
                return "real_estate"
            elif "Metro" in news["title"] or "infrastructure" in news["content"]:
                return "infrastructure"
            elif "PMAY" in news["title"] or "policy" in news["content"]:
                return "policy"
            return "general"

        categories = [categorize(item) for item in news_items]

        # Assert
        assert categories == ["real_estate", "infrastructure", "policy"]

    def test_multiple_sources_aggregation(self):
        """
        Test Case: PI-IT-008
        Test aggregation of news from multiple sources.
        Expected: News from all sources collected
        """
        # Arrange
        sources = ["ET", "Mint", "Housing.com"]
        news_by_source = {
            "ET": [{"title": "Article 1"}],
            "Mint": [{"title": "Article 2"}],
            "Housing.com": [{"title": "Article 3"}]
        }

        # Act - Aggregate
        all_news = []
        for source in sources:
            for item in news_by_source.get(source, []):
                item["source"] = source
                all_news.append(item)

        # Assert
        assert len(all_news) == 3
        assert len(set(item["source"] for item in all_news)) == 3

    def test_error_in_middle_of_pipeline(
        self,
        mock_news_scraper
    ):
        """
        Test Case: PI-IT-009
        Test graceful degradation when one scraper fails.
        Expected: Other scrapers continue
        """
        # Arrange
        scrapers = {
            "ET": Mock(scrape=Mock(return_value=[{"title": "Article 1"}])),
            "Mint": Mock(scrape=Mock(side_effect=Exception("Network error"))),
            "Housing": Mock(scrape=Mock(return_value=[{"title": "Article 2"}]))
        }

        # Act - Run scrapers with error handling
        results = []
        for name, scraper in scrapers.items():
            try:
                news = scraper.scrape()
                results.extend(news)
            except Exception as e:
                print(f"Scraper {name} failed: {e}")
                continue  # Continue with next scraper

        # Assert
        assert len(results) == 2  # Only ET and Housing succeeded
        assert results[0]["title"] == "Article 1"
        assert results[1]["title"] == "Article 2"

    def test_empty_pipeline_run(
        self,
        mock_telegram_api
    ):
        """
        Test Case: PI-IT-010
        Test pipeline behavior when no news found.
        Expected: Sends "No updates" message
        """
        # Arrange
        scraped_news = []  # No news found

        # Act
        if not scraped_news:
            message = "📭 No updates found in this cycle."
            response = mock_telegram_api.send_message(message)
        else:
            response = None

        # Assert
        assert response is not None
        assert response["ok"] == True


class TestPipelinePerformance:
    """Test pipeline performance and efficiency."""

    @pytest.mark.slow
    def test_pipeline_completes_under_2_minutes(self):
        """Test that full pipeline completes within time limit."""
        import time

        start_time = time.time()

        # Simulate pipeline steps
        time.sleep(0.1)  # Scraping
        time.sleep(0.05)  # Deduplication
        time.sleep(0.05)  # Categorization
        time.sleep(0.1)  # Notification

        end_time = time.time()
        duration = end_time - start_time

        assert duration < 120  # Less than 2 minutes

    def test_pipeline_handles_100_news_items(self):
        """Test pipeline can handle large volume of news."""
        news_items = [{"title": f"Article {i}"} for i in range(100)]

        # Process all items
        processed = len(news_items)

        assert processed == 100

    def test_pipeline_memory_usage(self):
        """Test pipeline memory usage stays reasonable."""
        import sys

        # Create large dataset
        news_items = [
            {"title": f"Article {i}", "content": "x" * 1000}
            for i in range(1000)
        ]

        # Check memory size
        size = sys.getsizeof(news_items)

        # Should be less than 10MB for 1000 items
        assert size < 10 * 1024 * 1024
