"""
Unit Tests for Deduplicator
Tests news deduplication logic

Auto-generated by Claude CLI
"""

import pytest
from unittest.mock import Mock, patch
import hashlib
from datetime import datetime, timedelta


pytestmark = pytest.mark.unit


class TestDeduplicator:
    """Test suite for Deduplicator class."""

    def test_detect_exact_duplicate(self):
        """
        Test Case: DD-UT-001
        Test detection of exact duplicate news items.
        Expected: Marked as duplicate
        """
        news1 = {
            "title": "Mumbai prices up 4.9%",
            "url": "https://example.com/news/123"
        }
        news2 = {
            "title": "Mumbai prices up 4.9%",
            "url": "https://example.com/news/123"
        }

        # Generate hashes
        hash1 = hashlib.md5(f"{news1['title']}{news1['url']}".encode()).hexdigest()
        hash2 = hashlib.md5(f"{news2['title']}{news2['url']}".encode()).hexdigest()

        assert hash1 == hash2

    def test_detect_similar_title(self):
        """
        Test Case: DD-UT-002
        Test detection of similar titles (85% similarity).
        Expected: Marked as duplicate
        """
        title1 = "Mumbai property prices up 4.9% in Q4"
        title2 = "Mumbai property prices up 4.9% in Q4 2026"

        # Simple similarity check
        similarity = self._calculate_similarity(title1, title2)
        assert similarity >= 0.85

    def test_allow_different_news(self):
        """
        Test Case: DD-UT-003
        Test that different news items are not marked as duplicates.
        Expected: Not marked as duplicate
        """
        news1 = {
            "title": "Mumbai prices up",
            "url": "https://example.com/news/123"
        }
        news2 = {
            "title": "Delhi prices down",
            "url": "https://example.com/news/456"
        }

        hash1 = hashlib.md5(f"{news1['title']}{news1['url']}".encode()).hexdigest()
        hash2 = hashlib.md5(f"{news2['title']}{news2['url']}".encode()).hexdigest()

        assert hash1 != hash2

    def test_hash_generation(self):
        """
        Test Case: DD-UT-004
        Test unique hash generation.
        Expected: Hash is consistent
        """
        news = {"title": "Test", "url": "https://test.com"}
        hash1 = hashlib.md5(f"{news['title']}{news['url']}".encode()).hexdigest()
        hash2 = hashlib.md5(f"{news['title']}{news['url']}".encode()).hexdigest()

        assert hash1 == hash2
        assert len(hash1) == 32  # MD5 hash length

    def test_url_normalization(self):
        """
        Test Case: DD-UT-005
        Test URL normalization for duplicate detection.
        Expected: Different URL formats recognized as same
        """
        url1 = "https://example.com/news/123"
        url2 = "http://example.com/news/123"
        url3 = "https://example.com/news/123/"

        # Normalize URLs
        normalized1 = url1.lower().rstrip('/').replace('http://', 'https://')
        normalized2 = url2.lower().rstrip('/').replace('http://', 'https://')
        normalized3 = url3.lower().rstrip('/').replace('http://', 'https://')

        assert normalized1 == normalized2 == normalized3

    def test_cleanup_old_cache(self):
        """
        Test Case: DD-UT-006
        Test cleanup of cache entries older than 24 hours.
        Expected: Old items removed
        """
        now = datetime.now()
        old_time = now - timedelta(hours=25)
        recent_time = now - timedelta(hours=12)

        cache = [
            {"hash": "abc123", "timestamp": old_time.isoformat()},
            {"hash": "def456", "timestamp": recent_time.isoformat()}
        ]

        # Filter items within 24 hours
        filtered = [
            item for item in cache
            if datetime.fromisoformat(item["timestamp"]) > (now - timedelta(hours=24))
        ]

        assert len(filtered) == 1
        assert filtered[0]["hash"] == "def456"

    def test_persistent_cache(self, temp_cache_file):
        """
        Test Case: DD-UT-007
        Test saving and loading cache file.
        Expected: Cache persists correctly
        """
        import json

        # Verify cache file exists and is readable
        assert temp_cache_file.exists()
        cache_data = json.loads(temp_cache_file.read_text())

        assert "sent_news" in cache_data
        assert "last_updated" in cache_data

    def test_edge_case_empty_title(self):
        """
        Test Case: DD-UT-008
        Test handling news with empty title.
        Expected: Handles gracefully
        """
        news = {"title": "", "url": "https://example.com/123"}
        hash_val = hashlib.md5(f"{news['title']}{news['url']}".encode()).hexdigest()

        assert hash_val is not None
        assert len(hash_val) == 32

    def test_unicode_in_title(self):
        """
        Test Case: DD-UT-009
        Test handling Unicode characters in title.
        Expected: Handles correctly
        """
        news = {"title": "मुंबई की कीमतें बढ़ीं 📈", "url": "https://example.com/123"}
        hash_val = hashlib.md5(f"{news['title']}{news['url']}".encode('utf-8')).hexdigest()

        assert hash_val is not None

    def test_duplicate_across_sources(self):
        """
        Test Case: DD-UT-010
        Test deduplication of same news from different sources.
        Expected: Deduplicates correctly
        """
        news1 = {"title": "Mumbai prices up", "source": "ET"}
        news2 = {"title": "Mumbai prices up", "source": "Mint"}

        # Should deduplicate based on title, not source
        hash1 = hashlib.md5(news1['title'].encode()).hexdigest()
        hash2 = hashlib.md5(news2['title'].encode()).hexdigest()

        assert hash1 == hash2

    # Helper method
    def _calculate_similarity(self, str1: str, str2: str) -> float:
        """Calculate similarity ratio between two strings."""
        from difflib import SequenceMatcher
        return SequenceMatcher(None, str1, str2).ratio()
