"""
Unit Tests for Celebrity Matcher
Tests celebrity name detection and property deal matching

Auto-generated by Claude CLI
"""

import pytest
import re
from unittest.mock import Mock, patch

pytestmark = pytest.mark.unit


class TestCelebrityMatcher:
    """Test suite for CelebrityMatcher class."""

    def test_match_celebrity_full_name(self, sample_celebrities_data):
        """
        Test Case: CM-UT-001
        Test matching celebrity full name in text.
        Expected: Match found
        """
        text = "Virat Kohli buys ₹34 Cr Worli apartment"
        celebs = sample_celebrities_data["celebrities"]

        # Find matching celebrity
        matched = [c for c in celebs if c["name"] in text]

        assert len(matched) == 1
        assert matched[0]["name"] == "Virat Kohli"

    def test_match_celebrity_alias(self, sample_celebrities_data):
        """
        Test Case: CM-UT-002
        Test matching celebrity by alias.
        Expected: Match found via alias
        """
        text = "King Kohli's new property in Mumbai"
        celebs = sample_celebrities_data["celebrities"]

        # Find by alias
        matched = []
        for celeb in celebs:
            if any(alias in text for alias in celeb["aliases"]):
                matched.append(celeb)

        assert len(matched) == 1
        assert matched[0]["name"] == "Virat Kohli"
        assert "King Kohli" in matched[0]["aliases"]

    def test_extract_amount_crore(self):
        """
        Test Case: CM-UT-003
        Test extracting amount in Crores.
        Expected: Amount extracted correctly
        """
        text = "Property worth ₹34 Cr purchased"
        pattern = r'₹(\d+(?:\.\d+)?)\s*Cr'
        match = re.search(pattern, text)

        assert match is not None
        amount = float(match.group(1))
        assert amount == 34.0

    def test_extract_amount_lakh(self):
        """
        Test Case: CM-UT-004
        Test extracting amount in Lakhs.
        Expected: Amount converted to Crores
        """
        text = "Stamp duty of ₹5.2 Lakh paid"
        pattern = r'₹(\d+(?:\.\d+)?)\s*Lakh'
        match = re.search(pattern, text)

        assert match is not None
        amount_lakh = float(match.group(1))
        amount_cr = amount_lakh / 100  # Convert to crores
        assert amount_cr == pytest.approx(0.052)

    def test_high_value_detection(self):
        """
        Test Case: CM-UT-005
        Test detection of high-value deals (>₹5 Cr).
        Expected: Flagged as high-value
        """
        amount = 34.0
        threshold = 5.0

        is_high_value = amount > threshold
        assert is_high_value == True

    def test_low_value_filtering(self):
        """
        Test Case: CM-UT-006
        Test filtering of low-value deals (<₹5 Cr).
        Expected: Not flagged
        """
        amount = 2.5
        threshold = 5.0

        is_high_value = amount > threshold
        assert is_high_value == False

    def test_multiple_celebrities(self, sample_celebrities_data):
        """
        Test Case: CM-UT-007
        Test multiple celebrities mentioned in same text.
        Expected: Both matched
        """
        text = "Virat Kohli and Shah Rukh Khan attend property launch"
        celebs = sample_celebrities_data["celebrities"]

        matched = [c for c in celebs if c["name"] in text]

        assert len(matched) == 2
        names = [c["name"] for c in matched]
        assert "Virat Kohli" in names
        assert "Shah Rukh Khan" in names

    def test_false_positive_prevention(self, sample_celebrities_data):
        """
        Test Case: CM-UT-008
        Test preventing false matches (e.g., "Kohli Road").
        Expected: No false match
        """
        text = "New project launches on Kohli Road, Mumbai"
        celebs = sample_celebrities_data["celebrities"]

        # Should not match "Kohli" in "Kohli Road"
        # Proper implementation would use word boundaries
        pattern = r'\bVirat Kohli\b'
        match = re.search(pattern, text)

        assert match is None  # No match for full name

    def test_confidence_scoring(self):
        """
        Test Case: CM-UT-009
        Test confidence scoring for matches.
        Expected: Returns 0-100 score
        """
        # Full name match = high confidence
        full_name_confidence = 95

        # Alias match = medium confidence
        alias_confidence = 75

        # Partial match = low confidence
        partial_confidence = 50

        assert 0 <= full_name_confidence <= 100
        assert 0 <= alias_confidence <= 100
        assert 0 <= partial_confidence <= 100
        assert full_name_confidence > alias_confidence > partial_confidence

    def test_celebrity_database_load(self, sample_celebrities_data):
        """
        Test Case: CM-UT-010
        Test loading celebrity database.
        Expected: All celebrities loaded
        """
        celebs = sample_celebrities_data["celebrities"]

        assert len(celebs) == 4
        assert all("name" in c for c in celebs)
        assert all("aliases" in c for c in celebs)
        assert all("category" in c for c in celebs)

    @pytest.mark.parametrize("text,expected_amount", [
        ("₹34 Cr", 34.0),
        ("₹5.2 Lakh", 0.052),
        ("₹100 Cr", 100.0),
        ("₹75.5 Cr", 75.5),
        ("₹2.5 Crore", 2.5),
    ])
    def test_extract_various_amount_formats(self, text, expected_amount):
        """Test extracting amounts in various formats."""
        pattern = r'₹(\d+(?:\.\d+)?)\s*(?:Cr|Crore|Lakh)'
        match = re.search(pattern, text)

        if match:
            amount = float(match.group(1))
            if 'Lakh' in text:
                amount = amount / 100
            assert abs(amount - expected_amount) < 0.01
