#!/usr/bin/env python3
"""
Auto-Fix Script with Claude API
Automatically fixes GitHub issues using Claude AI to write code
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from anthropic import Anthropic

def get_issue_details(issue_number):
    """Get issue details from GitHub"""
    import requests

    github_token = os.getenv('GH_TOKEN') or os.getenv('GITHUB_TOKEN')
    if not github_token:
        raise Exception("GH_TOKEN or GITHUB_TOKEN environment variable not set")

    github_repo = os.getenv('GITHUB_REPOSITORY', 'aijasminekaur11/khabri')

    headers = {
        'Authorization': f'token {github_token}',
        'Accept': 'application/vnd.github.v3+json'
    }

    url = f'https://api.github.com/repos/{github_repo}/issues/{issue_number}'
    try:
        response = requests.get(url, headers=headers, timeout=10)
    except requests.exceptions.Timeout:
        raise Exception(f"Request to GitHub API timed out for issue #{issue_number}")

    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"Failed to get issue: {response.status_code} - {response.text[:200]}")


def read_relevant_files():
    """Read relevant code files for context"""
    project_root = Path(__file__).parent.parent

    # Key files to provide context
    important_files = [
        'src/config/config_manager.py',
        'src/processors/news_processor.py',
        'src/scrapers/news_scraper.py',
        'src/notifiers/telegram_notifier.py',
    ]

    context = {}
    for file_path in important_files:
        full_path = project_root / file_path
        if full_path.exists():
            with open(full_path, 'r', encoding='utf-8') as f:
                context[file_path] = f.read()

    return context


def generate_fix_with_claude(issue_title, issue_body, code_context):
    """Use Claude API to generate actual code fix"""

    api_key = os.getenv('ANTHROPIC_API_KEY')
    if not api_key:
        raise Exception("ANTHROPIC_API_KEY not found")

    client = Anthropic(api_key=api_key)

    # Build comprehensive prompt for Claude
    prompt = f"""You are an expert Python developer. You need to fix this GitHub issue by writing actual code.

**Issue Title:** {issue_title}

**Issue Description:**
{issue_body}

**Current Codebase Context:**
{json.dumps(code_context, indent=2)}

**Your Task:**
1. Understand what the issue is asking for
2. Identify which file(s) need to be modified
3. Write the COMPLETE FIXED CODE for each file
4. Return your response in this EXACT JSON format:

{{
  "analysis": "Brief explanation of what you're fixing",
  "files_to_modify": [
    {{
      "path": "src/path/to/file.py",
      "action": "modify",
      "new_content": "COMPLETE FILE CONTENT HERE"
    }}
  ],
  "files_to_create": [
    {{
      "path": "src/path/to/newfile.py",
      "content": "COMPLETE FILE CONTENT HERE"
    }}
  ],
  "test_commands": ["pytest testing/test_cases/...", "..."],
  "summary": "One-sentence summary of the fix"
}}

**CRITICAL REQUIREMENTS:**
- Provide COMPLETE file contents, not just snippets
- Maintain existing code style and structure
- Include proper imports and error handling
- Add comments explaining complex logic
- Ensure code follows Python best practices

Return ONLY valid JSON, no markdown, no explanations outside the JSON.
"""

    print("🤖 Calling Claude API to generate fix...")

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=8000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    response_text = message.content[0].text

    # Parse JSON response
    try:
        # Remove markdown code blocks if present
        stripped = response_text.strip()
        if stripped.startswith("```"):
            first_newline = stripped.find("\n")
            last_fence = stripped.rfind("```")
            if first_newline != -1 and last_fence > first_newline:
                response_text = stripped[first_newline + 1:last_fence].strip()

        fix_plan = json.loads(response_text)
        return fix_plan
    except json.JSONDecodeError as e:
        print(f"❌ Failed to parse Claude response as JSON: {e}")
        print(f"Response: {response_text[:500]}")
        raise


def apply_fixes(fix_plan):
    """Apply the fixes generated by Claude"""
    import shutil

    project_root = Path(__file__).parent.parent

    print(f"\n📝 Analysis: {fix_plan['analysis']}")
    print(f"\n🔧 Summary: {fix_plan['summary']}")

    modified_files = []
    backup_paths = []

    def is_safe_path(path, root):
        """Ensure path is within the project root"""
        try:
            resolved = path.resolve()
            root_resolved = root.resolve()
            resolved.relative_to(root_resolved)
            return True
        except (OSError, ValueError):
            return False

    # Modify existing files
    for file_change in fix_plan.get('files_to_modify', []):
        file_path = project_root / file_change['path']

        if not is_safe_path(file_path, project_root):
            print(f"\n⚠️  Skipping unsafe path: {file_change['path']}")
            continue

        print(f"\n✏️  Modifying: {file_change['path']}")

        # Write to temp file first, then rename atomically
        file_path.parent.mkdir(parents=True, exist_ok=True)
        temp_path = file_path.with_suffix(file_path.suffix + '.tmp')

        # Backup original (retained until post-apply validation succeeds)
        backup_path = file_path.with_suffix(file_path.suffix + '.backup')
        if file_path.exists():
            shutil.copy2(file_path, backup_path)
            backup_paths.append(backup_path)

        # Write new content to temp, then rename
        with open(temp_path, 'w', encoding='utf-8') as f:
            f.write(file_change['new_content'])
        temp_path.replace(file_path)

        modified_files.append(str(file_path))

    # Create new files
    for new_file in fix_plan.get('files_to_create', []):
        file_path = project_root / new_file['path']

        if not is_safe_path(file_path, project_root):
            print(f"\n⚠️  Skipping unsafe path: {new_file['path']}")
            continue

        print(f"\n📄 Creating: {new_file['path']}")

        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_file['content'])

        modified_files.append(str(file_path))

    return modified_files, backup_paths


def cleanup_backups(backup_paths):
    """Remove backup files after successful validation"""
    for backup_path in backup_paths:
        try:
            if backup_path.exists():
                backup_path.unlink()
        except OSError as e:
            print(f"⚠️  Could not remove backup {backup_path}: {e}")


def _is_allowed_test_command(args):
    """Validate that a test command is safe to run"""
    if not args:
        return False
    if args[0] == 'pytest':
        return True
    if args[0] in ('python', 'python3') and len(args) >= 3 and args[1] == '-m' and args[2] == 'pytest':
        return True
    return False


def run_tests(test_commands):
    """Run tests to verify the fix (only allowed commands)"""
    import shlex
    print("\n🧪 Running tests...")

    for cmd in test_commands:
        args = shlex.split(cmd)
        if not _is_allowed_test_command(args):
            print(f"   ⚠️  Skipping disallowed command: {cmd}")
            continue

        print(f"   Running: {cmd}")
        try:
            result = subprocess.run(args, capture_output=True, text=True, timeout=300)
        except subprocess.TimeoutExpired:
            print(f"   ❌ Test timed out after 300s: {cmd}")
            return False

        if result.returncode != 0:
            print(f"   ❌ Test failed:")
            print(result.stdout)
            print(result.stderr)
            return False

    print("   ✅ All tests passed!")
    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python auto_fix_with_claude.py <issue_number>")
        sys.exit(1)

    issue_number = sys.argv[1]

    print("=" * 60)
    print(f"🤖 AUTO-FIX WITH CLAUDE AI")
    print(f"📋 Issue #{issue_number}")
    print("=" * 60)

    try:
        # Step 1: Get issue details
        print("\n📥 Fetching issue details from GitHub...")
        issue = get_issue_details(issue_number)

        print(f"   Title: {issue['title']}")
        print(f"   State: {issue['state']}")

        # Step 2: Read codebase context
        print("\n📚 Reading codebase for context...")
        code_context = read_relevant_files()
        print(f"   Loaded {len(code_context)} files for context")

        # Step 3: Generate fix with Claude
        print("\n🤖 Generating fix with Claude AI...")
        fix_plan = generate_fix_with_claude(
            issue['title'],
            issue.get('body') or '',
            code_context
        )

        # Step 4: Apply fixes
        print("\n🔧 Applying fixes...")
        modified_files, backup_paths = apply_fixes(fix_plan)

        # Step 5: Run tests
        test_commands = fix_plan.get('test_commands', [])
        if test_commands:
            tests_passed = run_tests(test_commands)
        else:
            print("\n⚠️  No tests specified, skipping test verification")
            tests_passed = True

        # Step 5b: Clean up backups after successful validation
        if tests_passed:
            cleanup_backups(backup_paths)
        else:
            print(f"\n⚠️  Tests failed — backup files retained for rollback")

        # Step 6: Output results
        print("\n" + "=" * 60)
        print("✅ AUTO-FIX COMPLETE!")
        print("=" * 60)
        print(f"\nModified files:")
        for f in modified_files:
            print(f"  - {f}")

        print(f"\nTests: {'✅ Passed' if tests_passed else '❌ Failed'}")
        print(f"\nSummary: {fix_plan['summary']}")

        # Write summary for GitHub Actions
        summary_file = Path('AUTO_FIX_SUMMARY.json')
        with open(summary_file, 'w') as f:
            json.dump({
                'success': True,
                'issue_number': issue_number,
                'modified_files': modified_files,
                'tests_passed': tests_passed,
                'summary': fix_plan['summary']
            }, f, indent=2)

        sys.exit(0 if tests_passed else 1)

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()

        # Write failure summary
        summary_file = Path('AUTO_FIX_SUMMARY.json')
        with open(summary_file, 'w') as f:
            json.dump({
                'success': False,
                'issue_number': issue_number,
                'error': str(e)
            }, f, indent=2)

        sys.exit(1)


if __name__ == "__main__":
    main()
