#!/usr/bin/env python3
"""
Auto-Fix Script with Claude API
Automatically fixes GitHub issues using Claude AI to write code
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from anthropic import Anthropic

def get_issue_details(issue_number):
    """Get issue details from GitHub"""
    import requests

    github_token = os.getenv('GH_TOKEN') or os.getenv('GITHUB_TOKEN')
    github_repo = os.getenv('GITHUB_REPOSITORY', 'aijasminekaur11/khabri')

    headers = {
        'Authorization': f'token {github_token}',
        'Accept': 'application/vnd.github.v3+json'
    }

    url = f'https://api.github.com/repos/{github_repo}/issues/{issue_number}'
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"Failed to get issue: {response.status_code}")


def read_relevant_files():
    """Read relevant code files for context"""
    project_root = Path(__file__).parent.parent

    # Key files to provide context
    important_files = [
        'src/config/config_manager.py',
        'src/processors/news_processor.py',
        'src/scrapers/news_scraper.py',
        'src/notifiers/telegram_notifier.py',
    ]

    context = {}
    for file_path in important_files:
        full_path = project_root / file_path
        if full_path.exists():
            with open(full_path, 'r', encoding='utf-8') as f:
                context[file_path] = f.read()

    return context


def generate_fix_with_claude(issue_title, issue_body, code_context):
    """Use Claude API to generate actual code fix"""

    api_key = os.getenv('ANTHROPIC_API_KEY')
    if not api_key:
        raise Exception("ANTHROPIC_API_KEY not found")

    client = Anthropic(api_key=api_key)

    # Build comprehensive prompt for Claude
    prompt = f"""You are an expert Python developer. You need to fix this GitHub issue by writing actual code.

**Issue Title:** {issue_title}

**Issue Description:**
{issue_body}

**Current Codebase Context:**
{json.dumps(code_context, indent=2)}

**Your Task:**
1. Understand what the issue is asking for
2. Identify which file(s) need to be modified
3. Write the COMPLETE FIXED CODE for each file
4. Return your response in this EXACT JSON format:

{{
  "analysis": "Brief explanation of what you're fixing",
  "files_to_modify": [
    {{
      "path": "src/path/to/file.py",
      "action": "modify",
      "new_content": "COMPLETE FILE CONTENT HERE"
    }}
  ],
  "files_to_create": [
    {{
      "path": "src/path/to/newfile.py",
      "content": "COMPLETE FILE CONTENT HERE"
    }}
  ],
  "test_commands": ["pytest testing/test_cases/...", "..."],
  "summary": "One-sentence summary of the fix"
}}

**CRITICAL REQUIREMENTS:**
- Provide COMPLETE file contents, not just snippets
- Maintain existing code style and structure
- Include proper imports and error handling
- Add comments explaining complex logic
- Ensure code follows Python best practices

Return ONLY valid JSON, no markdown, no explanations outside the JSON.
"""

    print("🤖 Calling Claude API to generate fix...")

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=8000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    response_text = message.content[0].text

    # Parse JSON response
    try:
        # Remove markdown code blocks if present
        if response_text.strip().startswith("```"):
            lines = response_text.split("\n")
            response_text = "\n".join(lines[1:-1])

        fix_plan = json.loads(response_text)
        return fix_plan
    except json.JSONDecodeError as e:
        print(f"❌ Failed to parse Claude response as JSON: {e}")
        print(f"Response: {response_text[:500]}")
        raise


def apply_fixes(fix_plan):
    """Apply the fixes generated by Claude"""
    project_root = Path(__file__).parent.parent

    print(f"\n📝 Analysis: {fix_plan['analysis']}")
    print(f"\n🔧 Summary: {fix_plan['summary']}")

    modified_files = []

    # Modify existing files
    for file_change in fix_plan.get('files_to_modify', []):
        file_path = project_root / file_change['path']

        print(f"\n✏️  Modifying: {file_change['path']}")

        # Backup original
        if file_path.exists():
            backup_path = file_path.with_suffix(file_path.suffix + '.backup')
            file_path.rename(backup_path)

        # Write new content
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(file_change['new_content'])

        modified_files.append(str(file_path))

    # Create new files
    for new_file in fix_plan.get('files_to_create', []):
        file_path = project_root / new_file['path']

        print(f"\n📄 Creating: {new_file['path']}")

        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_file['content'])

        modified_files.append(str(file_path))

    return modified_files


def run_tests(test_commands):
    """Run tests to verify the fix"""
    print("\n🧪 Running tests...")

    for cmd in test_commands:
        print(f"   Running: {cmd}")
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

        if result.returncode != 0:
            print(f"   ❌ Test failed:")
            print(result.stdout)
            print(result.stderr)
            return False

    print("   ✅ All tests passed!")
    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python auto_fix_with_claude.py <issue_number>")
        sys.exit(1)

    issue_number = sys.argv[1]

    print("=" * 60)
    print(f"🤖 AUTO-FIX WITH CLAUDE AI")
    print(f"📋 Issue #{issue_number}")
    print("=" * 60)

    try:
        # Step 1: Get issue details
        print("\n📥 Fetching issue details from GitHub...")
        issue = get_issue_details(issue_number)

        print(f"   Title: {issue['title']}")
        print(f"   State: {issue['state']}")

        # Step 2: Read codebase context
        print("\n📚 Reading codebase for context...")
        code_context = read_relevant_files()
        print(f"   Loaded {len(code_context)} files for context")

        # Step 3: Generate fix with Claude
        print("\n🤖 Generating fix with Claude AI...")
        fix_plan = generate_fix_with_claude(
            issue['title'],
            issue['body'],
            code_context
        )

        # Step 4: Apply fixes
        print("\n🔧 Applying fixes...")
        modified_files = apply_fixes(fix_plan)

        # Step 5: Run tests
        test_commands = fix_plan.get('test_commands', [])
        if test_commands:
            tests_passed = run_tests(test_commands)
        else:
            print("\n⚠️  No tests specified, skipping test verification")
            tests_passed = True

        # Step 6: Output results
        print("\n" + "=" * 60)
        print("✅ AUTO-FIX COMPLETE!")
        print("=" * 60)
        print(f"\nModified files:")
        for f in modified_files:
            print(f"  - {f}")

        print(f"\nTests: {'✅ Passed' if tests_passed else '❌ Failed'}")
        print(f"\nSummary: {fix_plan['summary']}")

        # Write summary for GitHub Actions
        summary_file = Path('AUTO_FIX_SUMMARY.json')
        with open(summary_file, 'w') as f:
            json.dump({
                'success': True,
                'issue_number': issue_number,
                'modified_files': modified_files,
                'tests_passed': tests_passed,
                'summary': fix_plan['summary']
            }, f, indent=2)

        sys.exit(0 if tests_passed else 1)

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()

        # Write failure summary
        summary_file = Path('AUTO_FIX_SUMMARY.json')
        with open(summary_file, 'w') as f:
            json.dump({
                'success': False,
                'issue_number': issue_number,
                'error': str(e)
            }, f, indent=2)

        sys.exit(1)


if __name__ == "__main__":
    main()
